#!/usr/bin/env python3
"""Convert icon_tab5.png to a 130×130 ARGB8888 LVGL C array.

The generated icon is checked into the repository. This helper makes its
source image and generated C array reproducible for the visual cockpit tile.
"""
import os
import sys
from PIL import Image

SRC = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..', 'icon_tab5.png'))
DST = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..', 'app', 'apps', 'app_reachy', 'reachy_icon.c'))
TILE = 130


def write_c(data: bytes, width: int, height: int, out: str) -> None:
    chunks = []
    for offset in range(0, len(data), 16):
        chunks.append(','.join(f'0x{data[offset + index]:02x}' for index in range(16)))
    body = ',\n    '.join(chunks)
    source = f'''// Auto-generated YRobot icon ({width}x{height} ARGB8888) — tool tile.
// Source: icon_tab5.png
// Generated by var/reachy/icon_convert.py — do not edit by hand.
#include <lvgl.h>

const uint8_t reachy_icon_pixel_data[{len(data)}] = {{
    {body}
}};

const lv_image_dsc_t reachy_icon = {{
    .header = {{
        .magic = LV_IMAGE_HEADER_MAGIC,
        .cf = LV_IMAGE_CF_ARGB8888,
        .flags = 0,
        .w = {width},
        .h = {height},
        .stride = {width * 4},
    }},
    .data_size = {len(data)},
    .data = reachy_icon_pixel_data,
}};
'''
    os.makedirs(os.path.dirname(out), exist_ok=True)
    with open(out, 'w') as handle:
        handle.write(source)


def main() -> int:
    if not os.path.exists(SRC):
        print(f'missing source: {SRC}', file=sys.stderr)
        return 1
    image = Image.open(SRC)
    image.thumbnail((TILE, TILE), Image.LANCZOS)
    canvas = Image.new('RGBA', (TILE, TILE), (0, 0, 0, 0))
    canvas.paste(image.convert('RGBA'), ((TILE - image.width) // 2, (TILE - image.height) // 2))
    write_c(canvas.tobytes(), TILE, TILE, DST)
    return 0


if __name__ == '__main__':
    sys.exit(main())
